### ISSUE TITLE
App crashing during the following step (collectionView.selectDelegate = self)

### ISSUE THREAD

**Issue by sandyzden** [bizz84/MVCarouselCollectionView#5]
i tried to implement as explained in the instructions. but the app crashes as the ViewController implementation when using (collectionView.selectDelegate = self)
Error : Thread 1: EXEC_BAD_ADDRESS(code=2, address = 0x.....)

**Comment by bizz84** [comment]
Thanks for reporting this, I made a note about this on the usage section on the Readme file.

The collectionView IBOutlet class must be declared as MVCarouselCollectionView in Interface Builder, otherwise the app will crash.

<img width="332" alt="ibclass" src="https://cloud.githubusercontent.com/assets/153167/9710857/5664f6cc-5536-11e5-9d5d-c8e4322fbc6f.png">
